name: use_remote_pkg
description: A sample command-line application.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  github_remote_pkg:
    git:
      url: https://github.com/ilopX/github_remote_pkg
      ref: 481a2f0b255bcc3b0953bdd378c73b46aaa4a6ed
      path: remote_pkg
