name: github_remote_pkg
description: A starting point for Dart libraries or applications.
# version: 1.0.0
homepage: https://github.com/ilopX/github_remote_pkg

environment:
  sdk: '>=2.10.0 <3.0.0'

